apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-sa
  namespace: app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flask-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes", "endpoints"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flask-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: flask-sa
    namespace: app
roleRef:
  kind: ClusterRole
  name: flask-cluster-role
  apiGroup: rbac.authorization.k8s.io
