apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-sa
  namespace: app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-role
  namespace: your-namespace
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-rolebinding
  namespace: your-namespace
subjects:
  - kind: ServiceAccount
    name: flask-sa
    namespace: your-namespace
roleRef:
  kind: Role
  name: flask-role
  apiGroup: rbac.authorization.k8s.io
