apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: flask-app
type: Opaque
data:
  DB_USER: Zmxhc2t1c2Vy       # base64 of "flaskuser"
  DB_PASS: c2VjdXJlcGFzcw==   # base64 of "securepass"
  API_KEY: YXBpa2V5MTIzNDU=   # base64 of "apikey12345"
